import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";

export async function updateSession(request: NextRequest) {
  let supabaseResponse = NextResponse.next({
    request,
  });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) =>
            request.cookies.set(name, value)
          );

          supabaseResponse = NextResponse.next({
            request,
          });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options)
          );


        },
      },
    }
  );

  // IMPORTANT: Avoid writing any logic between createServerClient and
  // supabase.auth.getUser(). A simple mistake could make it very hard to debug
  // issues with users being randomly logged out.

  const {
    data: { user },
  } = await supabase.auth.getUser();

  // Crawler-facing metadata routes MUST be listed here. They are generated by
  // Next (app/robots.ts, app/sitemap.ts, app/opengraph-image.tsx) and served
  // from the app, so the matcher in middleware.ts — which only exempts image
  // file extensions — routes them straight through this gate. A crawler carries
  // no auth cookie, so without these entries robots.txt and sitemap.xml answered
  // every search engine with a 307 to /login, and share cards fetched an image
  // that redirected to a login page.
  const CRAWLER_ROUTES = ["/robots.txt", "/sitemap.xml", "/opengraph-image"];

  const isPublicRoute =
    request.nextUrl.pathname === "/" ||
    CRAWLER_ROUTES.some((p) => request.nextUrl.pathname.startsWith(p)) ||
    request.nextUrl.pathname.startsWith("/catalog") ||
    request.nextUrl.pathname.startsWith("/login") ||
    request.nextUrl.pathname.startsWith("/auth") ||
    request.nextUrl.pathname.startsWith("/error") ||
    request.nextUrl.pathname.startsWith("/api/cron") ||
    request.nextUrl.pathname.startsWith("/api/health");

  if (!user && !isPublicRoute) {
    // no user, potentially respond by redirecting the user to the login page
    const url = request.nextUrl.clone();
    url.pathname = "/login";
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}

